import {
  ChapterItem,
  TopicItem,
  MCQItem,
  ClassItem,
  StudentProfile,
  TestItem,
} from "./portal-types";

export const INITIAL_CLASSES: ClassItem[] = [
  {
    id: "cls-1",
    name: "Class 12",
    section: "A",
    status: "active",
    student_count: 3,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "cls-2",
    name: "Class 11",
    section: "B",
    status: "active",
    student_count: 1,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
];

export const INITIAL_STUDENTS: (StudentProfile & { passwordHash: string })[] = [
  {
    id: "stu-1",
    login_id: "PHY-001",
    full_name: "Muhammad Ali",
    email: "ali@students.physlab.local",
    phone: "+92 300 1234567",
    class_id: "cls-1",
    class_name: "Class 12",
    section: "A",
    roll_number: "101",
    status: "active",
    force_password_change: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    passwordHash: "StudentPass123!",
  },
  {
    id: "stu-2",
    login_id: "PHY-002",
    full_name: "Sara Ahmed",
    email: "sara@students.physlab.local",
    phone: "+92 301 2345678",
    class_id: "cls-1",
    class_name: "Class 12",
    section: "A",
    roll_number: "102",
    status: "active",
    force_password_change: false,
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    passwordHash: "StudentPass123!",
  },
  {
    id: "stu-3",
    login_id: "PHY-003",
    full_name: "Bilal Khan",
    email: "bilal@students.physlab.local",
    phone: "+92 302 3456789",
    class_id: "cls-1",
    class_name: "Class 12",
    section: "A",
    roll_number: "103",
    status: "active",
    force_password_change: false,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    passwordHash: "StudentPass123!",
  },
  {
    id: "stu-4",
    login_id: "PHY-004",
    full_name: "Zainab Fatima",
    email: "zainab@students.physlab.local",
    phone: "+92 303 4567890",
    class_id: "cls-2",
    class_name: "Class 11",
    section: "B",
    roll_number: "201",
    status: "active",
    force_password_change: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    passwordHash: "TempPass999!",
  },
];

export const INITIAL_CHAPTERS: ChapterItem[] = [
  {
    id: "ch-1",
    name: "Measurements",
    chapter_number: 1,
    description: "Physical quantities, SI base & derived units, dimensions, and error analysis.",
    status: "active",
    display_order: 1,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: "ch-2",
    name: "Vectors and Equilibrium",
    chapter_number: 2,
    description: "Vector algebra, rectangular components, dot/cross products, and torque balance.",
    status: "active",
    display_order: 2,
    created_at: new Date(Date.now() - 39 * 86400000).toISOString(),
  },
  {
    id: "ch-3",
    name: "Motion and Force",
    chapter_number: 3,
    description: "Kinematics, Newton's laws of motion, momentum conservation, friction, and projectile motion.",
    status: "active",
    display_order: 3,
    created_at: new Date(Date.now() - 38 * 86400000).toISOString(),
  },
  {
    id: "ch-4",
    name: "Work and Energy",
    chapter_number: 4,
    description: "Work done by constant and variable force, work-energy theorem, and conservation of energy.",
    status: "active",
    display_order: 4,
    created_at: new Date(Date.now() - 37 * 86400000).toISOString(),
  },
  {
    id: "ch-5",
    name: "Circular Motion",
    chapter_number: 5,
    description: "Angular kinematics, centripetal acceleration, moment of inertia, and angular momentum.",
    status: "active",
    display_order: 5,
    created_at: new Date(Date.now() - 36 * 86400000).toISOString(),
  },
  {
    id: "ch-6",
    name: "Fluid Dynamics",
    chapter_number: 6,
    description: "Viscosity, Stokes' law, terminal velocity, equation of continuity, and Bernoulli's equation.",
    status: "active",
    display_order: 6,
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: "ch-7",
    name: "Oscillations",
    chapter_number: 7,
    description: "Simple harmonic motion, mass-spring system, simple pendulum, resonance, and damping.",
    status: "active",
    display_order: 7,
    created_at: new Date(Date.now() - 34 * 86400000).toISOString(),
  },
  {
    id: "ch-8",
    name: "Waves",
    chapter_number: 8,
    description: "Periodic waves, speed of sound in gases, superposition, standing waves, and Doppler effect.",
    status: "active",
    display_order: 8,
    created_at: new Date(Date.now() - 33 * 86400000).toISOString(),
  },
  {
    id: "ch-9",
    name: "Thermodynamics",
    chapter_number: 9,
    description: "Heat and work, first law of thermodynamics, molar heat capacities, Carnot engine, and entropy.",
    status: "active",
    display_order: 9,
    created_at: new Date(Date.now() - 32 * 86400000).toISOString(),
  },
  {
    id: "ch-10",
    name: "Electrostatics",
    chapter_number: 10,
    description: "Coulomb's law, electric field intensity, Gauss's law, electric potential, and capacitance.",
    status: "active",
    display_order: 10,
    created_at: new Date(Date.now() - 31 * 86400000).toISOString(),
  },
  {
    id: "ch-11",
    name: "Current Electricity",
    chapter_number: 11,
    description: "Electric current, Ohm's law, Kirchhoff's rules, potentiometer, and Wheatstone bridge.",
    status: "active",
    display_order: 11,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "ch-12",
    name: "Electromagnetism",
    chapter_number: 12,
    description: "Magnetic force on charge and current-carrying wire, Ampere's law, Faraday's law, and Lenz's law.",
    status: "active",
    display_order: 12,
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
  },
  {
    id: "ch-13",
    name: "Electronics",
    chapter_number: 13,
    description: "p-n junction diodes, rectification, transistors, operational amplifiers, and logic gates.",
    status: "active",
    display_order: 13,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: "ch-14",
    name: "Atomic Physics",
    chapter_number: 14,
    description: "Atomic spectra, Bohr's postulates, de Broglie hypothesis, and X-ray production.",
    status: "active",
    display_order: 14,
    created_at: new Date(Date.now() - 27 * 86400000).toISOString(),
  },
  {
    id: "ch-15",
    name: "Nuclear Physics",
    chapter_number: 15,
    description: "Mass defect and binding energy, radioactivity, radioactive decay law, and nuclear fission/fusion.",
    status: "active",
    display_order: 15,
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
  },
];

export const INITIAL_TOPICS: TopicItem[] = [
  { id: "top-1", chapter_id: "ch-3", name: "Newton's Laws", status: "active", created_at: new Date().toISOString() },
  { id: "top-2", chapter_id: "ch-3", name: "Momentum", status: "active", created_at: new Date().toISOString() },
  { id: "top-3", chapter_id: "ch-3", name: "Acceleration", status: "active", created_at: new Date().toISOString() },
  { id: "top-4", chapter_id: "ch-3", name: "Friction", status: "active", created_at: new Date().toISOString() },
  { id: "top-5", chapter_id: "ch-3", name: "Projectile Motion", status: "active", created_at: new Date().toISOString() },
  { id: "top-6", chapter_id: "ch-4", name: "Work Done", status: "active", created_at: new Date().toISOString() },
  { id: "top-7", chapter_id: "ch-4", name: "Conservation of Energy", status: "active", created_at: new Date().toISOString() },
  { id: "top-8", chapter_id: "ch-10", name: "Coulomb's Law", status: "active", created_at: new Date().toISOString() },
  { id: "top-9", chapter_id: "ch-11", name: "Ohm's Law", status: "active", created_at: new Date().toISOString() },
  { id: "top-10", chapter_id: "ch-14", name: "de Broglie Wavelength", status: "active", created_at: new Date().toISOString() },
];

export const INITIAL_MCQS: MCQItem[] = [
  {
    id: "mcq-1",
    chapter_id: "ch-3",
    chapter_name: "Motion and Force",
    topic_id: "top-1",
    topic_name: "Newton's Laws",
    question: "A constant force $F = 40\\text{ N}$ acts on a mass $m = 8\\text{ kg}$ initially at rest. What is the acceleration produced?",
    option_a: "$2.5\\text{ m/s}^2$",
    option_b: "$5.0\\text{ m/s}^2$",
    option_c: "$10.0\\text{ m/s}^2$",
    option_d: "$320\\text{ m/s}^2$",
    correct_answer: "B",
    explanation: "Using Newton's Second Law: $a = \\frac{F}{m} = \\frac{40\\text{ N}}{8\\text{ kg}} = 5.0\\text{ m/s}^2$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "mcq-2",
    chapter_id: "ch-3",
    chapter_name: "Motion and Force",
    topic_id: "top-2",
    topic_name: "Momentum",
    question: "A body of mass $2\\text{ kg}$ moves with velocity $v = 15\\text{ m/s}$. If an impulse of $10\\text{ N}\\cdot\\text{s}$ acts in the opposite direction, what is its new velocity?",
    option_a: "$5\\text{ m/s}$",
    option_b: "$10\\text{ m/s}$",
    option_c: "$20\\text{ m/s}$",
    option_d: "$25\\text{ m/s}$",
    correct_answer: "B",
    explanation: "Initial momentum $p_i = m v_i = 2 \\times 15 = 30\\text{ N}\\cdot\\text{s}$. Final momentum $p_f = p_i - J = 30 - 10 = 20\\text{ N}\\cdot\\text{s}$. Thus $v_f = \\frac{20}{2} = 10\\text{ m/s}$.",
    difficulty: "medium",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "mcq-3",
    chapter_id: "ch-3",
    chapter_name: "Motion and Force",
    topic_id: "top-5",
    topic_name: "Projectile Motion",
    question: "For a projectile launched at an angle $\\theta$ with speed $v_0$, at what angle is the maximum horizontal range achieved (ignoring air resistance)?",
    option_a: "$30^\\circ$",
    option_b: "$45^\\circ$",
    option_c: "$60^\\circ$",
    option_d: "$90^\\circ$",
    correct_answer: "B",
    explanation: "The range formula is $R = \\frac{v_0^2 \\sin(2\\theta)}{g}$. Range is maximized when $\\sin(2\\theta) = 1$, which gives $2\\theta = 90^\\circ \\implies \\theta = 45^\\circ$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 13 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 13 * 86400000).toISOString(),
  },
  {
    id: "mcq-4",
    chapter_id: "ch-3",
    chapter_name: "Motion and Force",
    topic_id: "top-3",
    topic_name: "Acceleration",
    question: "A vehicle accelerates uniformly from rest at $a = 3\\text{ m/s}^2$ for $t = 6\\text{ s}$. How far does it travel during this interval?",
    option_a: "$18\\text{ m}$",
    option_b: "$36\\text{ m}$",
    option_c: "$54\\text{ m}$",
    option_d: "$108\\text{ m}$",
    correct_answer: "C",
    explanation: "Using the second kinematic equation $s = v_i t + \\frac{1}{2} a t^2 = 0 + \\frac{1}{2}(3)(6)^2 = \\frac{1}{2}(3)(36) = 54\\text{ m}$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "mcq-5",
    chapter_id: "ch-3",
    chapter_name: "Motion and Force",
    topic_id: "top-4",
    topic_name: "Friction",
    question: "A block of mass $m = 5\\text{ kg}$ rests on a horizontal plane with static friction coefficient $\\mu_s = 0.4$. Taking $g = 9.8\\text{ m/s}^2$, what minimum horizontal force will initiate motion?",
    option_a: "$1.96\\text{ N}$",
    option_b: "$9.8\\text{ N}$",
    option_c: "$19.6\\text{ N}$",
    option_d: "$49.0\\text{ N}$",
    correct_answer: "C",
    explanation: "Maximum static friction $f_s = \\mu_s N = \\mu_s mg = 0.4 \\times 5 \\times 9.8 = 19.6\\text{ N}$.",
    difficulty: "medium",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: "mcq-6",
    chapter_id: "ch-4",
    chapter_name: "Work and Energy",
    topic_id: "top-6",
    topic_name: "Work Done",
    question: "A force $\\vec{F} = (3\\hat{i} + 4\\hat{j})\\text{ N}$ displaces an object by $\\vec{d} = (5\\hat{i} + 2\\hat{j})\\text{ m}$. What is the work done?",
    option_a: "$7\\text{ J}$",
    option_b: "$15\\text{ J}$",
    option_c: "$23\\text{ J}$",
    option_d: "$30\\text{ J}$",
    correct_answer: "C",
    explanation: "$W = \\vec{F} \\cdot \\vec{d} = (3)(5) + (4)(2) = 15 + 8 = 23\\text{ J}$.",
    difficulty: "medium",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "mcq-7",
    chapter_id: "ch-4",
    chapter_name: "Work and Energy",
    topic_id: "top-7",
    topic_name: "Conservation of Energy",
    question: "If the velocity of an object is tripled, by what factor does its kinetic energy increase?",
    option_a: "$3$",
    option_b: "$6$",
    option_c: "$9$",
    option_d: "$27$",
    correct_answer: "C",
    explanation: "Kinetic energy $K = \\frac{1}{2}mv^2$. Because $K \\propto v^2$, tripling $v$ multiplies $K$ by $3^2 = 9$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: "mcq-8",
    chapter_id: "ch-11",
    chapter_name: "Current Electricity",
    topic_id: "top-9",
    topic_name: "Ohm's Law",
    question: "According to Ohm's Law $V = IR$, what is the current flowing through a $240\\,\\Omega$ resistor connected across a $120\\text{ V}$ potential difference?",
    option_a: "$0.5\\text{ A}$",
    option_b: "$2.0\\text{ A}$",
    option_c: "$120\\text{ A}$",
    option_d: "$28800\\text{ A}$",
    correct_answer: "A",
    explanation: "$I = \\frac{V}{R} = \\frac{120\\text{ V}}{240\\,\\Omega} = 0.5\\text{ A}$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "mcq-9",
    chapter_id: "ch-14",
    chapter_name: "Atomic Physics",
    topic_id: "top-10",
    topic_name: "de Broglie Wavelength",
    question: "What is the de Broglie wavelength formula for a particle of linear momentum $p$, where $h$ is Planck's constant?",
    option_a: "$\\lambda = \\frac{p}{h}$",
    option_b: "$\\lambda = \\frac{h}{p}$",
    option_c: "$\\lambda = h \\cdot p$",
    option_d: "$\\lambda = \\frac{h}{p^2}$",
    correct_answer: "B",
    explanation: "Louis de Broglie proposed that matter exhibits wave-particle duality with wavelength $\\lambda = \\frac{h}{p}$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "mcq-10",
    chapter_id: "ch-10",
    chapter_name: "Electrostatics",
    topic_id: "top-8",
    topic_name: "Coulomb's Law",
    question: "If the separation distance between two point charges $q_1$ and $q_2$ is doubled, the electrostatic force $F$ between them becomes:",
    option_a: "$2F$",
    option_b: "$4F$",
    option_c: "$\\frac{F}{2}$",
    option_d: "$\\frac{F}{4}$",
    correct_answer: "D",
    explanation: "Coulomb's law states $F = \\frac{k q_1 q_2}{r^2}$. Because $F \\propto \\frac{1}{r^2}$, doubling $r$ decreases force to $\\frac{1}{2^2} = \\frac{1}{4}F$.",
    difficulty: "easy",
    marks: 1,
    negative_marks: 0.25,
    status: "active",
    version: 1,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
];

export const INITIAL_TESTS: TestItem[] = [
  {
    id: "test-1",
    title: "Chapter 3: Motion and Force Comprehensive Examination",
    description: "Evaluates kinematics, Newton's laws of motion, momentum conservation, friction, and projectile trajectories.",
    chapter_id: "ch-3",
    chapter_name: "Motion and Force",
    duration_minutes: 15,
    passing_percentage: 50,
    negative_marking: true,
    starts_at: new Date(Date.now() - 86400000).toISOString(),
    ends_at: new Date(Date.now() + 7 * 86400000).toISOString(),
    max_attempts: 2,
    randomize_questions: true,
    randomize_options: true,
    show_result: true,
    show_correct_answers: true,
    show_explanations: true,
    status: "active",
    question_ids: ["mcq-1", "mcq-2", "mcq-3", "mcq-4", "mcq-5"],
    total_marks: 5,
    question_count: 5,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "test-2",
    title: "Physics Fundamentals: Work, Energy & Electricity",
    description: "Covers work-energy theorem, power, Ohm's law, and modern physics wave properties.",
    chapter_id: "ch-4",
    chapter_name: "Work and Energy",
    duration_minutes: 20,
    passing_percentage: 60,
    negative_marking: false,
    starts_at: new Date(Date.now() - 86400000).toISOString(),
    ends_at: new Date(Date.now() + 14 * 86400000).toISOString(),
    max_attempts: 1,
    randomize_questions: false,
    randomize_options: false,
    show_result: true,
    show_correct_answers: false,
    show_explanations: false,
    status: "active",
    question_ids: ["mcq-6", "mcq-7", "mcq-8", "mcq-9", "mcq-10"],
    total_marks: 5,
    question_count: 5,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];
